name: bug_report
description: A widget that opens GitHub issues for Flutter applications. Supports image attachments. 
version: 0.0.1-dev.2
repository: https://github.com/Puepis/bug_report

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

issue_tracker: https://github.com/Puepis/bug_report/issues

dependencies:
  flutter:
    sdk: flutter
  github: ^7.0.0
  http: ^0.12.2
  device_info: ^0.4.2+4
  uuid: ^2.2.0
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
